services:
  - type: pserv
    name: oncare-backend
    env: go
    buildCommand: cd backend && go build -o server server.go
    startCommand: cd backend && ./server
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: oncare-db
          property: connectionString
      - key: MIGRATIONS_PATH
        value: file://pkg/db/migrations/postgres
      - key: JWT_SECRET
        generateValue: true
      - key: UPLOAD_PATH
        value: ./uploads

databases:
  - name: oncare-db
    databaseName: oncare
    user: oncare_user