services:
  - type: web
    name: oncare-backend
    env: go
    buildCommand: cd backend && go build -o server server.go
    startCommand: cd backend && ./server
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: oncare-db
          property: connectionString
      - key: MIGRATIONS_PATH
        value: file://pkg/db/migrations/postgres
      - key: JWT_SECRET
        generateValue: true
      - key: UPLOAD_PATH
        value: /opt/render/project/src/uploads
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1

databases:
  - name: oncare-db
    databaseName: oncare
    user: oncare